version: '3.8'

services:
  mongo:
    image: mongo
    volumes:
      - dbdata:/data/db

  backend:
    build: ../manual-docker/backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  frontend:
    build: ../manual-docker/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  dbdata:
